# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyl < Formula
  desc "Nylas Command Line Utility"
  homepage "https://nylas.com"
  version "1.0.0-preview6"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.nylas.com/nylas-cli/v1.0.0-preview6/nylas-cli_1.0.0-preview6_darwin_amd64.tar.gz"
      sha256 "c30f5d8d1cfd299589b472463de54e9acb9dd7783989e1cf925a66941a07a033"
    end
  end

  def install
    bin.install "nyl"
  end
end
