# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyl < Formula
  desc "Nylas Command Line Utility"
  homepage "https://nylas.com"
  version "1.0.0-preview2"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.nylas.com/nylas-cli/v1.0.0-preview2/nylas-cli_1.0.0-preview2_darwin_amd64.tar.gz"
      sha256 "bf9b837c365cbc45e0f9f28abc8af5ebdc7d7fa7ea10c75ad435635d7fecdb9a"
    end
  end

  def install
    bin.install "nylas-cli"
  end
end
