# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NylasCli < Formula
  desc "Nylas Command Line Utility"
  homepage "https://nylas.com"
  version "1.0.0-preview1"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.nylas.com/nylas-cli/v1.0.0-preview1/nylas-cli_1.0.0-preview1_darwin_amd64.tar.gz"
      sha256 "fdc7a8db5ccdc265fca31ea14a9cfe8a3ae313b98f8704af76a3a11aec241277"
    end
  end

  def install
    bin.install "nylas-cli"
  end
end
