# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NylasCli < Formula
  desc "Nylas Command Line Utility"
  homepage "https://nylas.com"
  version "1.0.0-preview1"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nylas/nylas-cli/releases/download/v1.0.0-preview1/nylas-cli_1.0.0-preview1_darwin_amd64.tar.gz"
      sha256 "ea536cb302c979bfd99b65948688c9c7b5b817a3520245e664d8ccccc6534a77"
    end
  end

  def install
    bin.install "nylas-cli"
  end
end
